/*
 * API для работы с CRM \"Мой Класс\"
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.moyklass.api.model;

import java.util.Date;
import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Статус клиента
 */
@ApiModel(description = "Статус клиента")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-04-15T19:21:47.202+03:00[Asia/Jerusalem]")
public class MKClientStatus {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Integer id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_STATE_ORDER = "stateOrder";
  @SerializedName(SERIALIZED_NAME_STATE_ORDER)
  private Integer stateOrder;

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private Date createdAt = null;

  /**
   * Код системного статуса
   */
  @JsonAdapter(SystemCodeEnum.Adapter.class)
  public enum SystemCodeEnum {
    REJECT("reject"),
    
    INACTIVE_CLIENT("inactive_client"),
    
    NEW("new"),
    
    BAD_LEAD("bad_lead"),
    
    CLIENT("client"),
    
    NULL("null");

    private String value;

    SystemCodeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static SystemCodeEnum fromValue(String value) {
      for (SystemCodeEnum b : SystemCodeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<SystemCodeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final SystemCodeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public SystemCodeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return SystemCodeEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_SYSTEM_CODE = "systemCode";
  @SerializedName(SERIALIZED_NAME_SYSTEM_CODE)
  private SystemCodeEnum systemCode;


   /**
   * ID
   * @return id
  **/
  @ApiModelProperty(example = "2", required = true, value = "ID")

  public Integer getId() {
    return id;
  }




  public MKClientStatus name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Название статуса
   * @return name
  **/
  @ApiModelProperty(example = "Учится", required = true, value = "Название статуса")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


   /**
   * Порядок сортировки
   * @return stateOrder
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "10", value = "Порядок сортировки")

  public Integer getStateOrder() {
    return stateOrder;
  }




  public MKClientStatus createdAt(Date createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Date getCreatedAt() {
    return createdAt;
  }


  public void setCreatedAt(Date createdAt) {
    this.createdAt = createdAt;
  }


  public MKClientStatus systemCode(SystemCodeEnum systemCode) {
    
    this.systemCode = systemCode;
    return this;
  }

   /**
   * Код системного статуса
   * @return systemCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "reject", value = "Код системного статуса")

  public SystemCodeEnum getSystemCode() {
    return systemCode;
  }


  public void setSystemCode(SystemCodeEnum systemCode) {
    this.systemCode = systemCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MKClientStatus clientStatus = (MKClientStatus) o;
    return Objects.equals(this.id, clientStatus.id) &&
        Objects.equals(this.name, clientStatus.name) &&
        Objects.equals(this.stateOrder, clientStatus.stateOrder) &&
        Objects.equals(this.createdAt, clientStatus.createdAt) &&
        Objects.equals(this.systemCode, clientStatus.systemCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, stateOrder, createdAt, systemCode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MKClientStatus {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    stateOrder: ").append(toIndentedString(stateOrder)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    systemCode: ").append(toIndentedString(systemCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

