/*
 * API для работы с CRM \"Мой Класс\"
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.moyklass.api.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * MKCompanyRestricted
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-04-15T19:21:47.202+03:00[Asia/Jerusalem]")
public class MKCompanyRestricted {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_CURRENCY = "currency";
  @SerializedName(SERIALIZED_NAME_CURRENCY)
  private String currency;


  public MKCompanyRestricted name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Название компании
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Название компании")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public MKCompanyRestricted currency(String currency) {
    
    this.currency = currency;
    return this;
  }

   /**
   * Валюта
   * @return currency
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Валюта")

  public String getCurrency() {
    return currency;
  }


  public void setCurrency(String currency) {
    this.currency = currency;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MKCompanyRestricted companyRestricted = (MKCompanyRestricted) o;
    return Objects.equals(this.name, companyRestricted.name) &&
        Objects.equals(this.currency, companyRestricted.currency);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, currency);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MKCompanyRestricted {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

