/*
 * API для работы с CRM \"Мой Класс\"
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.moyklass.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * MKCreateJoinResult
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-04-15T19:21:47.202+03:00[Asia/Jerusalem]")
public class MKCreateJoinResult {
  public static final String SERIALIZED_NAME_JOIN_ID = "joinId";
  @SerializedName(SERIALIZED_NAME_JOIN_ID)
  private Long joinId;

  public static final String SERIALIZED_NAME_LESSONS_COUNT = "lessonsCount";
  @SerializedName(SERIALIZED_NAME_LESSONS_COUNT)
  private Long lessonsCount;


  public MKCreateJoinResult joinId(Long joinId) {
    
    this.joinId = joinId;
    return this;
  }

   /**
   * ID созданной заявки
   * @return joinId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "ID созданной заявки")

  public Long getJoinId() {
    return joinId;
  }


  public void setJoinId(Long joinId) {
    this.joinId = joinId;
  }


  public MKCreateJoinResult lessonsCount(Long lessonsCount) {
    
    this.lessonsCount = lessonsCount;
    return this;
  }

   /**
   * Количество созданных записей на занятия
   * @return lessonsCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Количество созданных записей на занятия")

  public Long getLessonsCount() {
    return lessonsCount;
  }


  public void setLessonsCount(Long lessonsCount) {
    this.lessonsCount = lessonsCount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MKCreateJoinResult createJoinResult = (MKCreateJoinResult) o;
    return Objects.equals(this.joinId, createJoinResult.joinId) &&
        Objects.equals(this.lessonsCount, createJoinResult.lessonsCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(joinId, lessonsCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MKCreateJoinResult {\n");
    sb.append("    joinId: ").append(toIndentedString(joinId)).append("\n");
    sb.append("    lessonsCount: ").append(toIndentedString(lessonsCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

