/*
 * API для работы с CRM \"Мой Класс\"
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.moyklass.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;

/**
 * MKJoinStats
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-04-15T19:21:47.202+03:00[Asia/Jerusalem]")
public class MKJoinStats {
  public static final String SERIALIZED_NAME_VISITS = "visits";
  @SerializedName(SERIALIZED_NAME_VISITS)
  private Integer visits;

  public static final String SERIALIZED_NAME_FREE_VISITS = "freeVisits";
  @SerializedName(SERIALIZED_NAME_FREE_VISITS)
  private Integer freeVisits;

  public static final String SERIALIZED_NAME_NEXT_RECORD = "nextRecord";
  @SerializedName(SERIALIZED_NAME_NEXT_RECORD)
  private LocalDate nextRecord;

  public static final String SERIALIZED_NAME_LAST_VISIT = "lastVisit";
  @SerializedName(SERIALIZED_NAME_LAST_VISIT)
  private LocalDate lastVisit;

  public static final String SERIALIZED_NAME_LESSONS_LOST = "lessonsLost";
  @SerializedName(SERIALIZED_NAME_LESSONS_LOST)
  private Integer lessonsLost;

  public static final String SERIALIZED_NAME_TOTAL_PAYED = "totalPayed";
  @SerializedName(SERIALIZED_NAME_TOTAL_PAYED)
  private Long totalPayed;

  public static final String SERIALIZED_NAME_NON_PAYED_LESSONS = "nonPayedLessons";
  @SerializedName(SERIALIZED_NAME_NON_PAYED_LESSONS)
  private Integer nonPayedLessons;


  public MKJoinStats visits(Integer visits) {
    
    this.visits = visits;
    return this;
  }

   /**
   * Количество посещений
   * @return visits
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "5", value = "Количество посещений")

  public Integer getVisits() {
    return visits;
  }


  public void setVisits(Integer visits) {
    this.visits = visits;
  }


  public MKJoinStats freeVisits(Integer freeVisits) {
    
    this.freeVisits = freeVisits;
    return this;
  }

   /**
   * Количество бесплатных посещений
   * @return freeVisits
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "0", value = "Количество бесплатных посещений")

  public Integer getFreeVisits() {
    return freeVisits;
  }


  public void setFreeVisits(Integer freeVisits) {
    this.freeVisits = freeVisits;
  }


  public MKJoinStats nextRecord(LocalDate nextRecord) {
    
    this.nextRecord = nextRecord;
    return this;
  }

   /**
   * Ближайшая запись на занятие
   * @return nextRecord
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Ближайшая запись на занятие")

  public LocalDate getNextRecord() {
    return nextRecord;
  }


  public void setNextRecord(LocalDate nextRecord) {
    this.nextRecord = nextRecord;
  }


  public MKJoinStats lastVisit(LocalDate lastVisit) {
    
    this.lastVisit = lastVisit;
    return this;
  }

   /**
   * Последнее посещение
   * @return lastVisit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Sun Jun 02 03:00:00 IDT 2019", value = "Последнее посещение")

  public LocalDate getLastVisit() {
    return lastVisit;
  }


  public void setLastVisit(LocalDate lastVisit) {
    this.lastVisit = lastVisit;
  }


  public MKJoinStats lessonsLost(Integer lessonsLost) {
    
    this.lessonsLost = lessonsLost;
    return this;
  }

   /**
   * Количество пропущенных занятий
   * @return lessonsLost
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "Количество пропущенных занятий")

  public Integer getLessonsLost() {
    return lessonsLost;
  }


  public void setLessonsLost(Integer lessonsLost) {
    this.lessonsLost = lessonsLost;
  }


  public MKJoinStats totalPayed(Long totalPayed) {
    
    this.totalPayed = totalPayed;
    return this;
  }

   /**
   * Внесенная сумма (для групп с разовой оплатой)
   * @return totalPayed
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1000", value = "Внесенная сумма (для групп с разовой оплатой)")

  public Long getTotalPayed() {
    return totalPayed;
  }


  public void setTotalPayed(Long totalPayed) {
    this.totalPayed = totalPayed;
  }


  public MKJoinStats nonPayedLessons(Integer nonPayedLessons) {
    
    this.nonPayedLessons = nonPayedLessons;
    return this;
  }

   /**
   * Количество неоплаченных занятий (занятия в долг)
   * @return nonPayedLessons
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "Количество неоплаченных занятий (занятия в долг)")

  public Integer getNonPayedLessons() {
    return nonPayedLessons;
  }


  public void setNonPayedLessons(Integer nonPayedLessons) {
    this.nonPayedLessons = nonPayedLessons;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MKJoinStats joinStats = (MKJoinStats) o;
    return Objects.equals(this.visits, joinStats.visits) &&
        Objects.equals(this.freeVisits, joinStats.freeVisits) &&
        Objects.equals(this.nextRecord, joinStats.nextRecord) &&
        Objects.equals(this.lastVisit, joinStats.lastVisit) &&
        Objects.equals(this.lessonsLost, joinStats.lessonsLost) &&
        Objects.equals(this.totalPayed, joinStats.totalPayed) &&
        Objects.equals(this.nonPayedLessons, joinStats.nonPayedLessons);
  }

  @Override
  public int hashCode() {
    return Objects.hash(visits, freeVisits, nextRecord, lastVisit, lessonsLost, totalPayed, nonPayedLessons);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MKJoinStats {\n");
    sb.append("    visits: ").append(toIndentedString(visits)).append("\n");
    sb.append("    freeVisits: ").append(toIndentedString(freeVisits)).append("\n");
    sb.append("    nextRecord: ").append(toIndentedString(nextRecord)).append("\n");
    sb.append("    lastVisit: ").append(toIndentedString(lastVisit)).append("\n");
    sb.append("    lessonsLost: ").append(toIndentedString(lessonsLost)).append("\n");
    sb.append("    totalPayed: ").append(toIndentedString(totalPayed)).append("\n");
    sb.append("    nonPayedLessons: ").append(toIndentedString(nonPayedLessons)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

