/*
 * API для работы с CRM \"Мой Класс\"
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.moyklass.api.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.time.LocalDate;
import java.util.Date;
import java.util.List;
import java.util.Objects;

/**
 * MKJoin
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-04-15T19:21:47.202+03:00[Asia/Jerusalem]")
public class MKJoin {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Long id;

  public static final String SERIALIZED_NAME_USER_ID = "userId";
  @SerializedName(SERIALIZED_NAME_USER_ID)
  private Long userId;

  public static final String SERIALIZED_NAME_CLASS_ID = "classId";
  @SerializedName(SERIALIZED_NAME_CLASS_ID)
  private Long classId;

  public static final String SERIALIZED_NAME_PRICE = "price";
  @SerializedName(SERIALIZED_NAME_PRICE)
  private Long price;

  public static final String SERIALIZED_NAME_STATUS_ID = "statusId";
  @SerializedName(SERIALIZED_NAME_STATUS_ID)
  private Long statusId;

  public static final String SERIALIZED_NAME_STATUS_CHANGE_REASON_ID = "statusChangeReasonId";
  @SerializedName(SERIALIZED_NAME_STATUS_CHANGE_REASON_ID)
  private Integer statusChangeReasonId;

  public static final String SERIALIZED_NAME_AUTO_JOIN = "autoJoin";
  @SerializedName(SERIALIZED_NAME_AUTO_JOIN)
  private Boolean autoJoin = true;

  public static final String SERIALIZED_NAME_REMIND_DATE = "remindDate";
  @SerializedName(SERIALIZED_NAME_REMIND_DATE)
  private LocalDate remindDate;

  public static final String SERIALIZED_NAME_REMIND_SUM = "remindSum";
  @SerializedName(SERIALIZED_NAME_REMIND_SUM)
  private Long remindSum;

  public static final String SERIALIZED_NAME_MANAGER_ID = "managerId";
  @SerializedName(SERIALIZED_NAME_MANAGER_ID)
  private Long managerId;

  public static final String SERIALIZED_NAME_STATS = "stats";
  @SerializedName(SERIALIZED_NAME_STATS)
  private MKJoinStats stats;

  public static final String SERIALIZED_NAME_COMMENT = "comment";
  @SerializedName(SERIALIZED_NAME_COMMENT)
  private String comment;

  public static final String SERIALIZED_NAME_ADV_SOURCE_ID = "advSourceId";
  @SerializedName(SERIALIZED_NAME_ADV_SOURCE_ID)
  private Long advSourceId;

  public static final String SERIALIZED_NAME_CREATE_SOURCE_ID = "createSourceId";
  @SerializedName(SERIALIZED_NAME_CREATE_SOURCE_ID)
  private Long createSourceId;

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private Date createdAt = null;

  public static final String SERIALIZED_NAME_TAGS = "tags";
  @SerializedName(SERIALIZED_NAME_TAGS)
  private List<Long> tags = null;


   /**
   * ID заявки
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "300", value = "ID заявки")

  public Long getId() {
    return id;
  }




  public MKJoin userId(Long userId) {
    
    this.userId = userId;
    return this;
  }

   /**
   * ID ученика
   * @return userId
  **/
  @ApiModelProperty(example = "300", required = true, value = "ID ученика")

  public Long getUserId() {
    return userId;
  }


  public void setUserId(Long userId) {
    this.userId = userId;
  }


  public MKJoin classId(Long classId) {
    
    this.classId = classId;
    return this;
  }

   /**
   * ID группы
   * @return classId
  **/
  @ApiModelProperty(example = "400", required = true, value = "ID группы")

  public Long getClassId() {
    return classId;
  }


  public void setClassId(Long classId) {
    this.classId = classId;
  }


  public MKJoin price(Long price) {
    
    this.price = price;
    return this;
  }

   /**
   * Цена (для групп с разовой оплатой)
   * @return price
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "6000", value = "Цена (для групп с разовой оплатой)")

  public Long getPrice() {
    return price;
  }


  public void setPrice(Long price) {
    this.price = price;
  }


  public MKJoin statusId(Long statusId) {
    
    this.statusId = statusId;
    return this;
  }

   /**
   * Статус заявки
   * @return statusId
  **/
  @ApiModelProperty(example = "2", required = true, value = "Статус заявки")

  public Long getStatusId() {
    return statusId;
  }


  public void setStatusId(Long statusId) {
    this.statusId = statusId;
  }


  public MKJoin statusChangeReasonId(Integer statusChangeReasonId) {
    
    this.statusChangeReasonId = statusChangeReasonId;
    return this;
  }

   /**
   * ID причины смены статуса
   * @return statusChangeReasonId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "ID причины смены статуса")

  public Integer getStatusChangeReasonId() {
    return statusChangeReasonId;
  }


  public void setStatusChangeReasonId(Integer statusChangeReasonId) {
    this.statusChangeReasonId = statusChangeReasonId;
  }


  public MKJoin autoJoin(Boolean autoJoin) {
    
    this.autoJoin = autoJoin;
    return this;
  }

   /**
   * Автоматически записывать в статусе \&quot;Учится\&quot; на все занятия в группе
   * @return autoJoin
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "true", value = "Автоматически записывать в статусе \"Учится\" на все занятия в группе")

  public Boolean getAutoJoin() {
    return autoJoin;
  }


  public void setAutoJoin(Boolean autoJoin) {
    this.autoJoin = autoJoin;
  }


  public MKJoin remindDate(LocalDate remindDate) {
    
    this.remindDate = remindDate;
    return this;
  }

   /**
   * Срок оплаты долга
   * @return remindDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Fri Jun 14 03:00:00 IDT 2019", value = "Срок оплаты долга")

  public LocalDate getRemindDate() {
    return remindDate;
  }


  public void setRemindDate(LocalDate remindDate) {
    this.remindDate = remindDate;
  }


  public MKJoin remindSum(Long remindSum) {
    
    this.remindSum = remindSum;
    return this;
  }

   /**
   * Сумма долга к оплате
   * @return remindSum
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "500", value = "Сумма долга к оплате")

  public Long getRemindSum() {
    return remindSum;
  }


  public void setRemindSum(Long remindSum) {
    this.remindSum = remindSum;
  }


  public MKJoin managerId(Long managerId) {
    
    this.managerId = managerId;
    return this;
  }

   /**
   * ID ответственного сотрудника
   * @return managerId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "300", value = "ID ответственного сотрудника")

  public Long getManagerId() {
    return managerId;
  }


  public void setManagerId(Long managerId) {
    this.managerId = managerId;
  }


  public MKJoin stats(MKJoinStats stats) {
    
    this.stats = stats;
    return this;
  }

   /**
   * Get stats
   * @return stats
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public MKJoinStats getStats() {
    return stats;
  }


  public void setStats(MKJoinStats stats) {
    this.stats = stats;
  }


  public MKJoin comment(String comment) {
    
    this.comment = comment;
    return this;
  }

   /**
   * Комментарий
   * @return comment
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Комментарий")

  public String getComment() {
    return comment;
  }


  public void setComment(String comment) {
    this.comment = comment;
  }


  public MKJoin advSourceId(Long advSourceId) {
    
    this.advSourceId = advSourceId;
    return this;
  }

   /**
   * ID информационного источника (откуда ученик узнал о компании)
   * @return advSourceId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "23456", value = "ID информационного источника (откуда ученик узнал о компании)")

  public Long getAdvSourceId() {
    return advSourceId;
  }


  public void setAdvSourceId(Long advSourceId) {
    this.advSourceId = advSourceId;
  }


  public MKJoin createSourceId(Long createSourceId) {
    
    this.createSourceId = createSourceId;
    return this;
  }

   /**
   * ID способа заведения (как заведена карточка)
   * @return createSourceId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "56", value = "ID способа заведения (как заведена карточка)")

  public Long getCreateSourceId() {
    return createSourceId;
  }


  public void setCreateSourceId(Long createSourceId) {
    this.createSourceId = createSourceId;
  }


  public MKJoin createdAt(Date createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Date getCreatedAt() {
    return createdAt;
  }


  public void setCreatedAt(Date createdAt) {
    this.createdAt = createdAt;
  }


   /**
   * Теги
   * @return tags
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "[0,4]", value = "Теги")

  public List<Long> getTags() {
    return tags;
  }




  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MKJoin join = (MKJoin) o;
    return Objects.equals(this.id, join.id) &&
        Objects.equals(this.userId, join.userId) &&
        Objects.equals(this.classId, join.classId) &&
        Objects.equals(this.price, join.price) &&
        Objects.equals(this.statusId, join.statusId) &&
        Objects.equals(this.statusChangeReasonId, join.statusChangeReasonId) &&
        Objects.equals(this.autoJoin, join.autoJoin) &&
        Objects.equals(this.remindDate, join.remindDate) &&
        Objects.equals(this.remindSum, join.remindSum) &&
        Objects.equals(this.managerId, join.managerId) &&
        Objects.equals(this.stats, join.stats) &&
        Objects.equals(this.comment, join.comment) &&
        Objects.equals(this.advSourceId, join.advSourceId) &&
        Objects.equals(this.createSourceId, join.createSourceId) &&
        Objects.equals(this.createdAt, join.createdAt) &&
        Objects.equals(this.tags, join.tags);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, userId, classId, price, statusId, statusChangeReasonId, autoJoin, remindDate, remindSum, managerId, stats, comment, advSourceId, createSourceId, createdAt, tags);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MKJoin {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    classId: ").append(toIndentedString(classId)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    statusId: ").append(toIndentedString(statusId)).append("\n");
    sb.append("    statusChangeReasonId: ").append(toIndentedString(statusChangeReasonId)).append("\n");
    sb.append("    autoJoin: ").append(toIndentedString(autoJoin)).append("\n");
    sb.append("    remindDate: ").append(toIndentedString(remindDate)).append("\n");
    sb.append("    remindSum: ").append(toIndentedString(remindSum)).append("\n");
    sb.append("    managerId: ").append(toIndentedString(managerId)).append("\n");
    sb.append("    stats: ").append(toIndentedString(stats)).append("\n");
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("    advSourceId: ").append(toIndentedString(advSourceId)).append("\n");
    sb.append("    createSourceId: ").append(toIndentedString(createSourceId)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

