/*
 * API для работы с CRM \"Мой Класс\"
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.moyklass.api.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * MKLessonRecordEdit
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-04-15T19:21:47.202+03:00[Asia/Jerusalem]")
public class MKLessonRecordEdit {
  public static final String SERIALIZED_NAME_FREE = "free";
  @SerializedName(SERIALIZED_NAME_FREE)
  private Boolean free = false;

  public static final String SERIALIZED_NAME_VISIT = "visit";
  @SerializedName(SERIALIZED_NAME_VISIT)
  private Boolean visit = false;

  public static final String SERIALIZED_NAME_GOOD_REASON = "goodReason";
  @SerializedName(SERIALIZED_NAME_GOOD_REASON)
  private Boolean goodReason = false;


  public MKLessonRecordEdit free(Boolean free) {
    
    this.free = free;
    return this;
  }

   /**
   * Бесплатная запись (посещение для ученика будет бесплатным)
   * @return free
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "true", value = "Бесплатная запись (посещение для ученика будет бесплатным)")

  public Boolean getFree() {
    return free;
  }


  public void setFree(Boolean free) {
    this.free = free;
  }


  public MKLessonRecordEdit visit(Boolean visit) {
    
    this.visit = visit;
    return this;
  }

   /**
   * Статус посещения (true - ученик посетил занятие, false - пропустил)
   * @return visit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "false", value = "Статус посещения (true - ученик посетил занятие, false - пропустил)")

  public Boolean getVisit() {
    return visit;
  }


  public void setVisit(Boolean visit) {
    this.visit = visit;
  }


  public MKLessonRecordEdit goodReason(Boolean goodReason) {
    
    this.goodReason = goodReason;
    return this;
  }

   /**
   * Уважительная причина отсутствия (true - есть уважительная причина, false - нет)
   * @return goodReason
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "false", value = "Уважительная причина отсутствия (true - есть уважительная причина, false - нет)")

  public Boolean getGoodReason() {
    return goodReason;
  }


  public void setGoodReason(Boolean goodReason) {
    this.goodReason = goodReason;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MKLessonRecordEdit lessonRecordEdit = (MKLessonRecordEdit) o;
    return Objects.equals(this.free, lessonRecordEdit.free) &&
        Objects.equals(this.visit, lessonRecordEdit.visit) &&
        Objects.equals(this.goodReason, lessonRecordEdit.goodReason);
  }

  @Override
  public int hashCode() {
    return Objects.hash(free, visit, goodReason);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MKLessonRecordEdit {\n");
    sb.append("    free: ").append(toIndentedString(free)).append("\n");
    sb.append("    visit: ").append(toIndentedString(visit)).append("\n");
    sb.append("    goodReason: ").append(toIndentedString(goodReason)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

