/*
 * API для работы с CRM \"Мой Класс\"
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.moyklass.api.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * MKPaymentsPaging
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-04-15T19:21:47.202+03:00[Asia/Jerusalem]")
public class MKPaymentsPaging {
  public static final String SERIALIZED_NAME_TOTAL_ITEMS = "totalItems";
  @SerializedName(SERIALIZED_NAME_TOTAL_ITEMS)
  private Integer totalItems;

  public static final String SERIALIZED_NAME_TOTAL_SUM = "totalSum";
  @SerializedName(SERIALIZED_NAME_TOTAL_SUM)
  private Integer totalSum;


  public MKPaymentsPaging totalItems(Integer totalItems) {
    
    this.totalItems = totalItems;
    return this;
  }

   /**
   * Общее количество строк в результате, без учета limit и offset
   * @return totalItems
  **/
  @ApiModelProperty(example = "5", required = true, value = "Общее количество строк в результате, без учета limit и offset")

  public Integer getTotalItems() {
    return totalItems;
  }


  public void setTotalItems(Integer totalItems) {
    this.totalItems = totalItems;
  }


  public MKPaymentsPaging totalSum(Integer totalSum) {
    
    this.totalSum = totalSum;
    return this;
  }

   /**
   * Общая сумма общем результате
   * @return totalSum
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Общая сумма общем результате")

  public Integer getTotalSum() {
    return totalSum;
  }


  public void setTotalSum(Integer totalSum) {
    this.totalSum = totalSum;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MKPaymentsPaging paymentsPaging = (MKPaymentsPaging) o;
    return Objects.equals(this.totalItems, paymentsPaging.totalItems) &&
        Objects.equals(this.totalSum, paymentsPaging.totalSum);
  }

  @Override
  public int hashCode() {
    return Objects.hash(totalItems, totalSum);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MKPaymentsPaging {\n");
    sb.append("    totalItems: ").append(toIndentedString(totalItems)).append("\n");
    sb.append("    totalSum: ").append(toIndentedString(totalSum)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

