/*
 * API для работы с CRM \"Мой Класс\"
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.moyklass.api.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * MKTildaEvent
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-04-15T19:21:47.202+03:00[Asia/Jerusalem]")
public class MKTildaEvent {
  public static final String SERIALIZED_NAME_TRANID = "tranid";
  @SerializedName(SERIALIZED_NAME_TRANID)
  private String tranid;

  public static final String SERIALIZED_NAME_FORMID = "formid";
  @SerializedName(SERIALIZED_NAME_FORMID)
  private String formid;


  public MKTildaEvent tranid(String tranid) {
    
    this.tranid = tranid;
    return this;
  }

   /**
   * Уникальный номер заявки
   * @return tranid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Уникальный номер заявки")

  public String getTranid() {
    return tranid;
  }


  public void setTranid(String tranid) {
    this.tranid = tranid;
  }


  public MKTildaEvent formid(String formid) {
    
    this.formid = formid;
    return this;
  }

   /**
   * Номер блока, с которого была отправка
   * @return formid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Номер блока, с которого была отправка")

  public String getFormid() {
    return formid;
  }


  public void setFormid(String formid) {
    this.formid = formid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MKTildaEvent tildaEvent = (MKTildaEvent) o;
    return Objects.equals(this.tranid, tildaEvent.tranid) &&
        Objects.equals(this.formid, tildaEvent.formid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tranid, formid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MKTildaEvent {\n");
    sb.append("    tranid: ").append(toIndentedString(tranid)).append("\n");
    sb.append("    formid: ").append(toIndentedString(formid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

