/*
 * API для работы с CRM \"Мой Класс\"
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.moyklass.api.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * MKUserManager
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-04-15T19:21:47.202+03:00[Asia/Jerusalem]")
public class MKUserManager {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Long id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_IS_WORK = "isWork";
  @SerializedName(SERIALIZED_NAME_IS_WORK)
  private Boolean isWork;

  public static final String SERIALIZED_NAME_TEACH_FILIAL_IDS = "teachFilialIds";
  @SerializedName(SERIALIZED_NAME_TEACH_FILIAL_IDS)
  private List<Long> teachFilialIds = null;


   /**
   * ID
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "123", value = "ID")

  public Long getId() {
    return id;
  }




  public MKUserManager name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Полное имя
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Смолин Петр Михайлович", value = "Полное имя")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public MKUserManager isWork(Boolean isWork) {
    
    this.isWork = isWork;
    return this;
  }

   /**
   * Сотрудник доступен для выбора
   * @return isWork
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Сотрудник доступен для выбора")

  public Boolean getIsWork() {
    return isWork;
  }


  public void setIsWork(Boolean isWork) {
    this.isWork = isWork;
  }


  public MKUserManager teachFilialIds(List<Long> teachFilialIds) {
    
    this.teachFilialIds = teachFilialIds;
    return this;
  }

  public MKUserManager addTeachFilialIdsItem(Long teachFilialIdsItem) {
    if (this.teachFilialIds == null) {
      this.teachFilialIds = new ArrayList<>();
    }
    this.teachFilialIds.add(teachFilialIdsItem);
    return this;
  }

   /**
   * ID филиалов сотрудника, в которых он преподает
   * @return teachFilialIds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "ID филиалов сотрудника, в которых он преподает")

  public List<Long> getTeachFilialIds() {
    return teachFilialIds;
  }


  public void setTeachFilialIds(List<Long> teachFilialIds) {
    this.teachFilialIds = teachFilialIds;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MKUserManager userManager = (MKUserManager) o;
    return Objects.equals(this.id, userManager.id) &&
        Objects.equals(this.name, userManager.name) &&
        Objects.equals(this.isWork, userManager.isWork) &&
        Objects.equals(this.teachFilialIds, userManager.teachFilialIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, isWork, teachFilialIds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MKUserManager {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    isWork: ").append(toIndentedString(isWork)).append("\n");
    sb.append("    teachFilialIds: ").append(toIndentedString(teachFilialIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

