/*
 * API для работы с CRM \"Мой Класс\"
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.moyklass.api.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Статистика по занятиям
 */
@ApiModel(description = "Статистика по занятиям")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-04-15T19:21:47.202+03:00[Asia/Jerusalem]")
public class MKUserRestrictedLessonsStat {
  public static final String SERIALIZED_NAME_TOTAL_RECORDS = "totalRecords";
  @SerializedName(SERIALIZED_NAME_TOTAL_RECORDS)
  private Integer totalRecords;

  public static final String SERIALIZED_NAME_VISITS = "visits";
  @SerializedName(SERIALIZED_NAME_VISITS)
  private Integer visits;

  public static final String SERIALIZED_NAME_MISSES = "misses";
  @SerializedName(SERIALIZED_NAME_MISSES)
  private Integer misses;

  public static final String SERIALIZED_NAME_MISS_GOOD_REASON = "missGoodReason";
  @SerializedName(SERIALIZED_NAME_MISS_GOOD_REASON)
  private Integer missGoodReason;


  public MKUserRestrictedLessonsStat totalRecords(Integer totalRecords) {
    
    this.totalRecords = totalRecords;
    return this;
  }

   /**
   * Всего записей на занятие
   * @return totalRecords
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Всего записей на занятие")

  public Integer getTotalRecords() {
    return totalRecords;
  }


  public void setTotalRecords(Integer totalRecords) {
    this.totalRecords = totalRecords;
  }


  public MKUserRestrictedLessonsStat visits(Integer visits) {
    
    this.visits = visits;
    return this;
  }

   /**
   * Посещений
   * @return visits
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Посещений")

  public Integer getVisits() {
    return visits;
  }


  public void setVisits(Integer visits) {
    this.visits = visits;
  }


  public MKUserRestrictedLessonsStat misses(Integer misses) {
    
    this.misses = misses;
    return this;
  }

   /**
   * Пропусков
   * @return misses
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Пропусков")

  public Integer getMisses() {
    return misses;
  }


  public void setMisses(Integer misses) {
    this.misses = misses;
  }


  public MKUserRestrictedLessonsStat missGoodReason(Integer missGoodReason) {
    
    this.missGoodReason = missGoodReason;
    return this;
  }

   /**
   * Пропусков по уважительной причине
   * @return missGoodReason
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Пропусков по уважительной причине")

  public Integer getMissGoodReason() {
    return missGoodReason;
  }


  public void setMissGoodReason(Integer missGoodReason) {
    this.missGoodReason = missGoodReason;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MKUserRestrictedLessonsStat userRestrictedLessonsStat = (MKUserRestrictedLessonsStat) o;
    return Objects.equals(this.totalRecords, userRestrictedLessonsStat.totalRecords) &&
        Objects.equals(this.visits, userRestrictedLessonsStat.visits) &&
        Objects.equals(this.misses, userRestrictedLessonsStat.misses) &&
        Objects.equals(this.missGoodReason, userRestrictedLessonsStat.missGoodReason);
  }

  @Override
  public int hashCode() {
    return Objects.hash(totalRecords, visits, misses, missGoodReason);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MKUserRestrictedLessonsStat {\n");
    sb.append("    totalRecords: ").append(toIndentedString(totalRecords)).append("\n");
    sb.append("    visits: ").append(toIndentedString(visits)).append("\n");
    sb.append("    misses: ").append(toIndentedString(misses)).append("\n");
    sb.append("    missGoodReason: ").append(toIndentedString(missGoodReason)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

