/*
 * API для работы с CRM \"Мой Класс\"
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.moyklass.api.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * MKUser
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-04-15T19:21:47.202+03:00[Asia/Jerusalem]")
public class MKUser {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Long id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_EMAIL = "email";
  @SerializedName(SERIALIZED_NAME_EMAIL)
  private String email;

  public static final String SERIALIZED_NAME_PHONE = "phone";
  @SerializedName(SERIALIZED_NAME_PHONE)
  private String phone;

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_BALANS = "balans";
  @SerializedName(SERIALIZED_NAME_BALANS)
  private Integer balans;

  public static final String SERIALIZED_NAME_RESPONSIBLE_ID = "responsibleId";
  @SerializedName(SERIALIZED_NAME_RESPONSIBLE_ID)
  private Long responsibleId;

  public static final String SERIALIZED_NAME_ADV_SOURCE_ID = "advSourceId";
  @SerializedName(SERIALIZED_NAME_ADV_SOURCE_ID)
  private Long advSourceId = null;

  public static final String SERIALIZED_NAME_CREATE_SOURCE_ID = "createSourceId";
  @SerializedName(SERIALIZED_NAME_CREATE_SOURCE_ID)
  private Long createSourceId = null;

  public static final String SERIALIZED_NAME_CLIENT_STATE_ID = "clientStateId";
  @SerializedName(SERIALIZED_NAME_CLIENT_STATE_ID)
  private Long clientStateId;

  public static final String SERIALIZED_NAME_FILIALS = "filials";
  @SerializedName(SERIALIZED_NAME_FILIALS)
  private List<Long> filials = null;

  public static final String SERIALIZED_NAME_ATTRIBUTES = "attributes";
  @SerializedName(SERIALIZED_NAME_ATTRIBUTES)
  private List<Object> attributes = null;

  public static final String SERIALIZED_NAME_JOINS = "joins";
  @SerializedName(SERIALIZED_NAME_JOINS)
  private List<MKUserJoin> joins = null;

   /**
   * ID ученика в системе
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "123456", value = "ID ученика в системе")

  public Long getId() {
    return id;
  }




  public MKUser name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Полное имя ученика
   * @return name
  **/
  @ApiModelProperty(example = "Иванов Петр Александрович", required = true, value = "Полное имя ученика")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public MKUser email(String email) {
    
    this.email = email;
    return this;
  }

   /**
   * Email ученика
   * @return email
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "ivanov@site.com", value = "Email ученика")

  public String getEmail() {
    return email;
  }


  public void setEmail(String email) {
    this.email = email;
  }


  public MKUser phone(String phone) {
    
    this.phone = phone;
    return this;
  }

   /**
   * Номер телефона ученика
   * @return phone
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "79001234567", value = "Номер телефона ученика")

  public String getPhone() {
    return phone;
  }


  public void setPhone(String phone) {
    this.phone = phone;
  }


   /**
   * Дата создания
   * @return createdAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2019-06-12T13:00:12Z", value = "Дата создания")

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }




   /**
   * Баланс ученика
   * @return balans
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "100", value = "Баланс ученика")

  public Integer getBalans() {
    return balans;
  }




  public MKUser responsibleId(Long responsibleId) {
    
    this.responsibleId = responsibleId;
    return this;
  }

   /**
   * ID ответственного менеджера
   * @return responsibleId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "12322", value = "ID ответственного менеджера")

  public Long getResponsibleId() {
    return responsibleId;
  }


  public void setResponsibleId(Long responsibleId) {
    this.responsibleId = responsibleId;
  }


  public MKUser advSourceId(Long advSourceId) {
    
    this.advSourceId = advSourceId;
    return this;
  }

   /**
   * Get advSourceId
   * @return advSourceId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getAdvSourceId() {
    return advSourceId;
  }


  public void setAdvSourceId(Long advSourceId) {
    this.advSourceId = advSourceId;
  }


  public MKUser createSourceId(Long createSourceId) {
    
    this.createSourceId = createSourceId;
    return this;
  }

   /**
   * Get createSourceId
   * @return createSourceId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getCreateSourceId() {
    return createSourceId;
  }


  public void setCreateSourceId(Long createSourceId) {
    this.createSourceId = createSourceId;
  }


  public MKUser clientStateId(Long clientStateId) {
    
    this.clientStateId = clientStateId;
    return this;
  }

   /**
   * ID статуса клиента
   * @return clientStateId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "10", value = "ID статуса клиента")

  public Long getClientStateId() {
    return clientStateId;
  }


  public void setClientStateId(Long clientStateId) {
    this.clientStateId = clientStateId;
  }


  public MKUser filials(List<Long> filials) {
    
    this.filials = filials;
    return this;
  }

  public MKUser addFilialsItem(Long filialsItem) {
    if (this.filials == null) {
      this.filials = new ArrayList<>();
    }
    this.filials.add(filialsItem);
    return this;
  }

   /**
   * ID филиалов ученика
   * @return filials
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "ID филиалов ученика")

  public List<Long> getFilials() {
    return filials;
  }


  public void setFilials(List<Long> filials) {
    this.filials = filials;
  }


  public MKUser attributes(List<Object> attributes) {
    
    this.attributes = attributes;
    return this;
  }

  public MKUser addAttributesItem(Object attributesItem) {
    if (this.attributes == null) {
      this.attributes = new ArrayList<>();
    }
    this.attributes.add(attributesItem);
    return this;
  }

   /**
   * Дополнительные атрибуты ученика
   * @return attributes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Дополнительные атрибуты ученика")

  public List<Object> getAttributes() {
    return attributes;
  }


  public void setAttributes(List<Object> attributes) {
    this.attributes = attributes;
  }

  public List<MKUserJoin> getJoins() {
    return joins;
  }

  public void setJoins(List<MKUserJoin> joins) {
    this.joins = joins;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MKUser user = (MKUser) o;
    return Objects.equals(this.id, user.id) &&
        Objects.equals(this.name, user.name) &&
        Objects.equals(this.email, user.email) &&
        Objects.equals(this.phone, user.phone) &&
        Objects.equals(this.createdAt, user.createdAt) &&
        Objects.equals(this.balans, user.balans) &&
        Objects.equals(this.responsibleId, user.responsibleId) &&
        Objects.equals(this.advSourceId, user.advSourceId) &&
        Objects.equals(this.createSourceId, user.createSourceId) &&
        Objects.equals(this.clientStateId, user.clientStateId) &&
        Objects.equals(this.filials, user.filials) &&
        Objects.equals(this.attributes, user.attributes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, email, phone, createdAt, balans, responsibleId, advSourceId, createSourceId, clientStateId, filials, attributes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MKUser {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    balans: ").append(toIndentedString(balans)).append("\n");
    sb.append("    responsibleId: ").append(toIndentedString(responsibleId)).append("\n");
    sb.append("    advSourceId: ").append(toIndentedString(advSourceId)).append("\n");
    sb.append("    createSourceId: ").append(toIndentedString(createSourceId)).append("\n");
    sb.append("    clientStateId: ").append(toIndentedString(clientStateId)).append("\n");
    sb.append("    filials: ").append(toIndentedString(filials)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

