/*
 * API для работы с CRM \"Мой Класс\"
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.moyklass.api.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.time.LocalDate;
import java.util.Objects;

/**
 * Платеж
 */
@ApiModel(description = "Платеж")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-04-15T19:21:47.202+03:00[Asia/Jerusalem]")
public class MKUserPayment {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Long id;

  public static final String SERIALIZED_NAME_USER_ID = "userId";
  @SerializedName(SERIALIZED_NAME_USER_ID)
  private Long userId = null;

  public static final String SERIALIZED_NAME_DATE = "date";
  @SerializedName(SERIALIZED_NAME_DATE)
  private LocalDate date;

  public static final String SERIALIZED_NAME_SUMMA = "summa";
  @SerializedName(SERIALIZED_NAME_SUMMA)
  private Long summa;

  public static final String SERIALIZED_NAME_USER_SUBSCRIPTION_ID = "userSubscriptionId";
  @SerializedName(SERIALIZED_NAME_USER_SUBSCRIPTION_ID)
  private Long userSubscriptionId;


   /**
   * ID
   * @return id
  **/
  @ApiModelProperty(example = "1", required = true, value = "ID")

  public Long getId() {
    return id;
  }




  public MKUserPayment userId(Long userId) {
    
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  @ApiModelProperty(required = true, value = "")

  public Long getUserId() {
    return userId;
  }


  public void setUserId(Long userId) {
    this.userId = userId;
  }


  public MKUserPayment date(LocalDate date) {
    
    this.date = date;
    return this;
  }

   /**
   * Дата платежа
   * @return date
  **/
  @ApiModelProperty(example = "Fri Jun 14 03:00:00 IDT 2019", required = true, value = "Дата платежа")

  public LocalDate getDate() {
    return date;
  }


  public void setDate(LocalDate date) {
    this.date = date;
  }


  public MKUserPayment summa(Long summa) {
    
    this.summa = summa;
    return this;
  }

   /**
   * Сумма
   * @return summa
  **/
  @ApiModelProperty(example = "1990", required = true, value = "Сумма")

  public Long getSumma() {
    return summa;
  }


  public void setSumma(Long summa) {
    this.summa = summa;
  }


  public MKUserPayment userSubscriptionId(Long userSubscriptionId) {
    
    this.userSubscriptionId = userSubscriptionId;
    return this;
  }

   /**
   * ID абонемента
   * @return userSubscriptionId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1504", value = "ID абонемента")

  public Long getUserSubscriptionId() {
    return userSubscriptionId;
  }


  public void setUserSubscriptionId(Long userSubscriptionId) {
    this.userSubscriptionId = userSubscriptionId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MKUserPayment userPayment = (MKUserPayment) o;
    return Objects.equals(this.id, userPayment.id) &&
        Objects.equals(this.userId, userPayment.userId) &&
        Objects.equals(this.date, userPayment.date) &&
        Objects.equals(this.summa, userPayment.summa) &&
        Objects.equals(this.userSubscriptionId, userPayment.userSubscriptionId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, userId, date, summa, userSubscriptionId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MKUserPayment {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    summa: ").append(toIndentedString(summa)).append("\n");
    sb.append("    userSubscriptionId: ").append(toIndentedString(userSubscriptionId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

