/*
 * API для работы с CRM \"Мой Класс\"
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.moyklass.api.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Занятие
 */
@ApiModel(description = "Занятие")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-04-15T19:21:47.202+03:00[Asia/Jerusalem]")
public class MKUserLesson {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Long id;

  public static final String SERIALIZED_NAME_DATE = "date";
  @SerializedName(SERIALIZED_NAME_DATE)
  private LocalDate date;

  public static final String SERIALIZED_NAME_BEGIN_TIME = "beginTime";
  @SerializedName(SERIALIZED_NAME_BEGIN_TIME)
  private String beginTime;

  public static final String SERIALIZED_NAME_END_TIME = "endTime";
  @SerializedName(SERIALIZED_NAME_END_TIME)
  private String endTime;

  public static final String SERIALIZED_NAME_FILIAL_ID = "filialId";
  @SerializedName(SERIALIZED_NAME_FILIAL_ID)
  private Long filialId = null;

  public static final String SERIALIZED_NAME_ROOM_ID = "roomId";
  @SerializedName(SERIALIZED_NAME_ROOM_ID)
  private Long roomId;

  public static final String SERIALIZED_NAME_CLASS_ID = "classId";
  @SerializedName(SERIALIZED_NAME_CLASS_ID)
  private Long classId = null;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private Integer status;

  public static final String SERIALIZED_NAME_FREE_RECORDS = "freeRecords";
  @SerializedName(SERIALIZED_NAME_FREE_RECORDS)
  private Integer freeRecords;

  public static final String SERIALIZED_NAME_TOPIC = "topic";
  @SerializedName(SERIALIZED_NAME_TOPIC)
  private String topic;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_TEACHER_IDS = "teacherIds";
  @SerializedName(SERIALIZED_NAME_TEACHER_IDS)
  private List<Long> teacherIds = null;

  public static final String SERIALIZED_NAME_RECORDS = "records";
  @SerializedName(SERIALIZED_NAME_RECORDS)
  private List<MKUserLessonRecord> records = null;

  public static final String SERIALIZED_NAME_HOME_TASK = "homeTask";
  @SerializedName(SERIALIZED_NAME_HOME_TASK)
  private MKHomeTask homeTask;

  public static final String SERIALIZED_NAME_LESSON_TASK = "lessonTask";
  @SerializedName(SERIALIZED_NAME_LESSON_TASK)
  private MKLessonTask lessonTask;

  public static final String SERIALIZED_NAME_COMMENTS = "comments";
  @SerializedName(SERIALIZED_NAME_COMMENTS)
  private List<MKUserComment> comments = null;

  public static final String SERIALIZED_NAME_MARKS = "marks";
  @SerializedName(SERIALIZED_NAME_MARKS)
  private List<MKMark> marks = null;

  public static final String SERIALIZED_NAME_PARAMS = "params";
  @SerializedName(SERIALIZED_NAME_PARAMS)
  private Object params;


   /**
   * ID
   * @return id
  **/
  @ApiModelProperty(example = "1", required = true, value = "ID")

  public Long getId() {
    return id;
  }




  public MKUserLesson date(LocalDate date) {
    
    this.date = date;
    return this;
  }

   /**
   * Дата проведения
   * @return date
  **/
  @ApiModelProperty(example = "Fri Jun 14 03:00:00 IDT 2019", required = true, value = "Дата проведения")

  public LocalDate getDate() {
    return date;
  }


  public void setDate(LocalDate date) {
    this.date = date;
  }


  public MKUserLesson beginTime(String beginTime) {
    
    this.beginTime = beginTime;
    return this;
  }

   /**
   * Время начала
   * @return beginTime
  **/
  @ApiModelProperty(example = "09:00", required = true, value = "Время начала")

  public String getBeginTime() {
    return beginTime;
  }


  public void setBeginTime(String beginTime) {
    this.beginTime = beginTime;
  }


  public MKUserLesson endTime(String endTime) {
    
    this.endTime = endTime;
    return this;
  }

   /**
   * Время окончания
   * @return endTime
  **/
  @ApiModelProperty(example = "09:40", required = true, value = "Время окончания")

  public String getEndTime() {
    return endTime;
  }


  public void setEndTime(String endTime) {
    this.endTime = endTime;
  }


  public MKUserLesson filialId(Long filialId) {
    
    this.filialId = filialId;
    return this;
  }

   /**
   * Get filialId
   * @return filialId
  **/
  @ApiModelProperty(required = true, value = "")

  public Long getFilialId() {
    return filialId;
  }


  public void setFilialId(Long filialId) {
    this.filialId = filialId;
  }


  public MKUserLesson roomId(Long roomId) {
    
    this.roomId = roomId;
    return this;
  }

   /**
   * ID аудитории
   * @return roomId
  **/
  @ApiModelProperty(example = "100", required = true, value = "ID аудитории")

  public Long getRoomId() {
    return roomId;
  }


  public void setRoomId(Long roomId) {
    this.roomId = roomId;
  }


  public MKUserLesson classId(Long classId) {
    
    this.classId = classId;
    return this;
  }

   /**
   * Get classId
   * @return classId
  **/
  @ApiModelProperty(required = true, value = "")

  public Long getClassId() {
    return classId;
  }


  public void setClassId(Long classId) {
    this.classId = classId;
  }


  public MKUserLesson status(Integer status) {
    
    this.status = status;
    return this;
  }

   /**
   * Статус занятия. 1 - Проведено, 0 - Не проведено
   * @return status
  **/
  @ApiModelProperty(example = "1", required = true, value = "Статус занятия. 1 - Проведено, 0 - Не проведено")

  public Integer getStatus() {
    return status;
  }


  public void setStatus(Integer status) {
    this.status = status;
  }


  public MKUserLesson freeRecords(Integer freeRecords) {
    
    this.freeRecords = freeRecords;
    return this;
  }

   /**
   * Количество свободных мест
   * @return freeRecords
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "10", value = "Количество свободных мест")

  public Integer getFreeRecords() {
    return freeRecords;
  }


  public void setFreeRecords(Integer freeRecords) {
    this.freeRecords = freeRecords;
  }


  public MKUserLesson topic(String topic) {
    
    this.topic = topic;
    return this;
  }

   /**
   * Тема занятия
   * @return topic
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Планеты солнечной системы.", value = "Тема занятия")

  public String getTopic() {
    return topic;
  }


  public void setTopic(String topic) {
    this.topic = topic;
  }


  public MKUserLesson description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Описание занятия
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "На этом занятии узнаем, сколько планет в солнечной системе и как появилась луна.", value = "Описание занятия")

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public MKUserLesson teacherIds(List<Long> teacherIds) {
    
    this.teacherIds = teacherIds;
    return this;
  }

  public MKUserLesson addTeacherIdsItem(Long teacherIdsItem) {
    if (this.teacherIds == null) {
      this.teacherIds = new ArrayList<>();
    }
    this.teacherIds.add(teacherIdsItem);
    return this;
  }

   /**
   * Преподаватели
   * @return teacherIds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Преподаватели")

  public List<Long> getTeacherIds() {
    return teacherIds;
  }


  public void setTeacherIds(List<Long> teacherIds) {
    this.teacherIds = teacherIds;
  }


  public MKUserLesson records(List<MKUserLessonRecord> records) {
    
    this.records = records;
    return this;
  }

  public MKUserLesson addRecordsItem(MKUserLessonRecord recordsItem) {
    if (this.records == null) {
      this.records = new ArrayList<>();
    }
    this.records.add(recordsItem);
    return this;
  }

   /**
   * Записи на занятие
   * @return records
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Записи на занятие")

  public List<MKUserLessonRecord> getRecords() {
    return records;
  }


  public void setRecords(List<MKUserLessonRecord> records) {
    this.records = records;
  }


  public MKUserLesson homeTask(MKHomeTask homeTask) {
    
    this.homeTask = homeTask;
    return this;
  }

   /**
   * Get homeTask
   * @return homeTask
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public MKHomeTask getHomeTask() {
    return homeTask;
  }


  public void setHomeTask(MKHomeTask homeTask) {
    this.homeTask = homeTask;
  }


  public MKUserLesson lessonTask(MKLessonTask lessonTask) {
    
    this.lessonTask = lessonTask;
    return this;
  }

   /**
   * Get lessonTask
   * @return lessonTask
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public MKLessonTask getLessonTask() {
    return lessonTask;
  }


  public void setLessonTask(MKLessonTask lessonTask) {
    this.lessonTask = lessonTask;
  }


  public MKUserLesson comments(List<MKUserComment> comments) {
    
    this.comments = comments;
    return this;
  }

  public MKUserLesson addCommentsItem(MKUserComment commentsItem) {
    if (this.comments == null) {
      this.comments = new ArrayList<>();
    }
    this.comments.add(commentsItem);
    return this;
  }

   /**
   * Комментарии к занятию
   * @return comments
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Комментарии к занятию")

  public List<MKUserComment> getComments() {
    return comments;
  }


  public void setComments(List<MKUserComment> comments) {
    this.comments = comments;
  }


  public MKUserLesson marks(List<MKMark> marks) {
    
    this.marks = marks;
    return this;
  }

  public MKUserLesson addMarksItem(MKMark marksItem) {
    if (this.marks == null) {
      this.marks = new ArrayList<>();
    }
    this.marks.add(marksItem);
    return this;
  }

   /**
   * Оценки за занятие
   * @return marks
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Оценки за занятие")

  public List<MKMark> getMarks() {
    return marks;
  }


  public void setMarks(List<MKMark> marks) {
    this.marks = marks;
  }


  public MKUserLesson params(Object params) {
    
    this.params = params;
    return this;
  }

   /**
   * Доп информация о занятии
   * @return params
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Доп информация о занятии")

  public Object getParams() {
    return params;
  }


  public void setParams(Object params) {
    this.params = params;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MKUserLesson userLesson = (MKUserLesson) o;
    return Objects.equals(this.id, userLesson.id) &&
        Objects.equals(this.date, userLesson.date) &&
        Objects.equals(this.beginTime, userLesson.beginTime) &&
        Objects.equals(this.endTime, userLesson.endTime) &&
        Objects.equals(this.filialId, userLesson.filialId) &&
        Objects.equals(this.roomId, userLesson.roomId) &&
        Objects.equals(this.classId, userLesson.classId) &&
        Objects.equals(this.status, userLesson.status) &&
        Objects.equals(this.freeRecords, userLesson.freeRecords) &&
        Objects.equals(this.topic, userLesson.topic) &&
        Objects.equals(this.description, userLesson.description) &&
        Objects.equals(this.teacherIds, userLesson.teacherIds) &&
        Objects.equals(this.records, userLesson.records) &&
        Objects.equals(this.homeTask, userLesson.homeTask) &&
        Objects.equals(this.lessonTask, userLesson.lessonTask) &&
        Objects.equals(this.comments, userLesson.comments) &&
        Objects.equals(this.marks, userLesson.marks) &&
        Objects.equals(this.params, userLesson.params);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, date, beginTime, endTime, filialId, roomId, classId, status, freeRecords, topic, description, teacherIds, records, homeTask, lessonTask, comments, marks, params);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MKUserLesson {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    beginTime: ").append(toIndentedString(beginTime)).append("\n");
    sb.append("    endTime: ").append(toIndentedString(endTime)).append("\n");
    sb.append("    filialId: ").append(toIndentedString(filialId)).append("\n");
    sb.append("    roomId: ").append(toIndentedString(roomId)).append("\n");
    sb.append("    classId: ").append(toIndentedString(classId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    freeRecords: ").append(toIndentedString(freeRecords)).append("\n");
    sb.append("    topic: ").append(toIndentedString(topic)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    teacherIds: ").append(toIndentedString(teacherIds)).append("\n");
    sb.append("    records: ").append(toIndentedString(records)).append("\n");
    sb.append("    homeTask: ").append(toIndentedString(homeTask)).append("\n");
    sb.append("    lessonTask: ").append(toIndentedString(lessonTask)).append("\n");
    sb.append("    comments: ").append(toIndentedString(comments)).append("\n");
    sb.append("    marks: ").append(toIndentedString(marks)).append("\n");
    sb.append("    params: ").append(toIndentedString(params)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

