/*
 * API для работы с CRM \"Мой Класс\"
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.moyklass.api.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * MKUserFilial
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-04-15T19:21:47.202+03:00[Asia/Jerusalem]")
public class MKUserFilial {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Long id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_CITY = "city";
  @SerializedName(SERIALIZED_NAME_CITY)
  private String city;

  public static final String SERIALIZED_NAME_ADDRESS = "address";
  @SerializedName(SERIALIZED_NAME_ADDRESS)
  private String address;

  public static final String SERIALIZED_NAME_SHORT_NAME = "shortName";
  @SerializedName(SERIALIZED_NAME_SHORT_NAME)
  private String shortName;

  public static final String SERIALIZED_NAME_TIMEZONE = "timezone";
  @SerializedName(SERIALIZED_NAME_TIMEZONE)
  private String timezone;


   /**
   * ID
   * @return id
  **/
  @ApiModelProperty(example = "1", required = true, value = "ID")

  public Long getId() {
    return id;
  }




  public MKUserFilial name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Название
   * @return name
  **/
  @ApiModelProperty(example = "Московский филиал на Коуровской", required = true, value = "Название")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public MKUserFilial city(String city) {
    
    this.city = city;
    return this;
  }

   /**
   * Город
   * @return city
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Москва", value = "Город")

  public String getCity() {
    return city;
  }


  public void setCity(String city) {
    this.city = city;
  }


  public MKUserFilial address(String address) {
    
    this.address = address;
    return this;
  }

   /**
   * Адрес
   * @return address
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Ул. Коуровская, 5, оф 506, 5 этаж", value = "Адрес")

  public String getAddress() {
    return address;
  }


  public void setAddress(String address) {
    this.address = address;
  }


  public MKUserFilial shortName(String shortName) {
    
    this.shortName = shortName;
    return this;
  }

   /**
   * Короткое название
   * @return shortName
  **/
  @ApiModelProperty(example = "МСК", required = true, value = "Короткое название")

  public String getShortName() {
    return shortName;
  }


  public void setShortName(String shortName) {
    this.shortName = shortName;
  }


  public MKUserFilial timezone(String timezone) {
    
    this.timezone = timezone;
    return this;
  }

   /**
   * Временная зона
   * @return timezone
  **/
  @ApiModelProperty(example = "Europe/Moscow", required = true, value = "Временная зона")

  public String getTimezone() {
    return timezone;
  }


  public void setTimezone(String timezone) {
    this.timezone = timezone;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MKUserFilial userFilial = (MKUserFilial) o;
    return Objects.equals(this.id, userFilial.id) &&
        Objects.equals(this.name, userFilial.name) &&
        Objects.equals(this.city, userFilial.city) &&
        Objects.equals(this.address, userFilial.address) &&
        Objects.equals(this.shortName, userFilial.shortName) &&
        Objects.equals(this.timezone, userFilial.timezone);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, city, address, shortName, timezone);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MKUserFilial {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    shortName: ").append(toIndentedString(shortName)).append("\n");
    sb.append("    timezone: ").append(toIndentedString(timezone)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

