/*
 * API для работы с CRM \"Мой Класс\"
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.moyklass.api.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Date;
import java.util.Objects;

/**
 * MKUserComment
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-04-15T19:21:47.202+03:00[Asia/Jerusalem]")
public class MKUserComment {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Long id;

  public static final String SERIALIZED_NAME_USER_ID = "userId";
  @SerializedName(SERIALIZED_NAME_USER_ID)
  private Long userId;

  public static final String SERIALIZED_NAME_LESSON_ID = "lessonId";
  @SerializedName(SERIALIZED_NAME_LESSON_ID)
  private Long lessonId;

  public static final String SERIALIZED_NAME_COMMENT = "comment";
  @SerializedName(SERIALIZED_NAME_COMMENT)
  private String comment;

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private Date createdAt = null;


  public MKUserComment id(Long id) {
    
    this.id = id;
    return this;
  }

   /**
   * ID комментария
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "ID комментария")

  public Long getId() {
    return id;
  }


  public void setId(Long id) {
    this.id = id;
  }


  public MKUserComment userId(Long userId) {
    
    this.userId = userId;
    return this;
  }

   /**
   * ID пользователя
   * @return userId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "ID пользователя")

  public Long getUserId() {
    return userId;
  }


  public void setUserId(Long userId) {
    this.userId = userId;
  }


  public MKUserComment lessonId(Long lessonId) {
    
    this.lessonId = lessonId;
    return this;
  }

   /**
   * ID занятия
   * @return lessonId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "ID занятия")

  public Long getLessonId() {
    return lessonId;
  }


  public void setLessonId(Long lessonId) {
    this.lessonId = lessonId;
  }


  public MKUserComment comment(String comment) {
    
    this.comment = comment;
    return this;
  }

   /**
   * Текст комментария
   * @return comment
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Текст комментария")

  public String getComment() {
    return comment;
  }


  public void setComment(String comment) {
    this.comment = comment;
  }


  public MKUserComment createdAt(Date createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Date getCreatedAt() {
    return createdAt;
  }


  public void setCreatedAt(Date createdAt) {
    this.createdAt = createdAt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MKUserComment userComment = (MKUserComment) o;
    return Objects.equals(this.id, userComment.id) &&
        Objects.equals(this.userId, userComment.userId) &&
        Objects.equals(this.lessonId, userComment.lessonId) &&
        Objects.equals(this.comment, userComment.comment) &&
        Objects.equals(this.createdAt, userComment.createdAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, userId, lessonId, comment, createdAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MKUserComment {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    lessonId: ").append(toIndentedString(lessonId)).append("\n");
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

